spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/treasure
    username: treasure
    password: treasure
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

feature:
  integrations:
    payments:
      enabled: false
    notifications:
      enabled: false
