global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
    scrape_interval: 15s
    scrape_timeout: 10s

  # User Service
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8083']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Payment Service
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8081']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Treasure Service
  - job_name: 'treasure-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['treasure-service:8082']
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL Exporter for User Service DB
  - job_name: 'postgres-user'
    static_configs:
      - targets: ['postgres-user:5432']
    scrape_interval: 30s

  # PostgreSQL Exporter for Payment Service DB
  - job_name: 'postgres-payment'
    static_configs:
      - targets: ['postgres-payment:5432']
    scrape_interval: 30s

  # PostgreSQL Exporter for Treasure Service DB
  - job_name: 'postgres-treasure'
    static_configs:
      - targets: ['postgres-treasure:5432']
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

  # Node.js Frontend (if metrics endpoint is available)
  - job_name: 'frontend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s
    scrape_timeout: 10s
