---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: msd-infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: msd-infrastructure
data:
  vault.hcl: |
    ui = true
    disable_mlock = true
    
    storage "file" {
      path = "/vault/data"
    }
    
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    
    api_addr = "http://0.0.0.0:8200"
    cluster_addr = "http://0.0.0.0:8201"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
  namespace: msd-infrastructure
type: Opaque
data:
  VAULT_DEV_ROOT_TOKEN_ID: cm9vdC10b2tlbi0xMjM= # root-token-123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: msd-infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.15
        ports:
        - containerPort: 8200
        - containerPort: 8201
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          valueFrom:
            secretKeyRef:
              name: vault-secret
              key: VAULT_DEV_ROOT_TOKEN_ID
        - name: VAULT_DEV_LISTEN_ADDRESS
          value: "0.0.0.0:8200"
        command:
        - vault
        - server
        - -dev
        - -dev-root-token-id=$(VAULT_DEV_ROOT_TOKEN_ID)
        - -dev-listen-address=0.0.0.0:8200
        volumeMounts:
        - name: vault-storage
          mountPath: /vault/data
        - name: vault-config
          mountPath: /vault/config
        livenessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      volumes:
      - name: vault-storage
        persistentVolumeClaim:
          claimName: vault-pvc
      - name: vault-config
        configMap:
          name: vault-config
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: msd-infrastructure
spec:
  selector:
    app: vault
  ports:
  - name: http
    port: 8200
    targetPort: 8200
  - name: cluster
    port: 8201
    targetPort: 8201
  type: ClusterIP
