---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: msd-treasure-hunt
data:
  SERVER_PORT: "8081"
  KEYCLOAK_URL: "http://keycloak.msd-infrastructure.svc.cluster.local:8080"
  KEYCLOAK_REALM: "treasure-hunt"
  KEYCLOAK_CLIENT_ID: "auth-service"
  KEYCLOAK_AUTH_SERVER_URL: "http://keycloak.msd-infrastructure.svc.cluster.local:8080"
  KEYCLOAK_ADMIN_USERNAME: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin123"
  VAULT_URL: "http://vault.msd-infrastructure.svc.cluster.local:8200"
  REDIS_URL: "redis://redis.msd-infrastructure.svc.cluster.local:6379"
  REDIS_HOST: "redis.msd-infrastructure.svc.cluster.local"
  REDIS_PORT: "6379"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "kubernetes"
  SPRING_PROFILES_ACTIVE: "bootstrap"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: msd-treasure-hunt
type: Opaque
data:
  KEYCLOAK_CLIENT_SECRET: YXV0aC1zZXJ2aWNlLXNlY3JldA== # auth-service-secret
  VAULT_TOKEN: cm9vdC10b2tlbi0xMjM= # root-token-123
  JWT_SECRET: and0LXNlY3JldC1rZXktZm9yLWF1dGgtc2VydmljZQ== # jwt-secret-key-for-auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: msd-treasure-hunt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: auth-service-config
        - secretRef:
            name: auth-service-secret
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
      initContainers:
      - name: wait-for-keycloak
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          until nc -z keycloak.msd-infrastructure.svc.cluster.local 8080; do
            echo "Waiting for Keycloak..."
            sleep 5
          done
          echo "Keycloak is ready!"
      - name: wait-for-vault
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          until nc -z vault.msd-infrastructure.svc.cluster.local 8200; do
            echo "Waiting for Vault..."
            sleep 5
          done
          echo "Vault is ready!"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: msd-treasure-hunt
spec:
  selector:
    app: auth-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
