---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: msd-treasure-hunt
data:
  NEXT_PUBLIC_API_URL: "http://api-gateway.msd-treasure-hunt.svc.cluster.local:8080"
  NEXT_PUBLIC_APP_NAME: "Dream Rider"
  NEXT_PUBLIC_APP_SUBTITLE: "MySillyDreams"
  NODE_ENV: "production"
  PORT: "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: msd-treasure-hunt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-config
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
      initContainers:
      - name: wait-for-api-gateway
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          until nc -z api-gateway.msd-treasure-hunt.svc.cluster.local 8080; do
            echo "Waiting for API Gateway..."
            sleep 5
          done
          echo "API Gateway is ready!"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: msd-treasure-hunt
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
